[package]
name = "copilot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
reqwest = { version = "0.12.12", features = ["rustls-tls"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
